export const learntUiUx = {
  title: "Let's summarise what we learnt so far",
  description:
    "In more simpler terms, for a software development or mobile app development project, Discovery Workshop is the pre-development stage of gathering and sharing relevant project information between client and the project team. The platform for information sharing could be on site/off site meetups and online conferences.",
  learntItems: [
    {
      title: "Discover and Devise",
      image: "/images/discover-device.jpg",
      alternate: "Discover and Devise",
      analyst: "/images/icons/analyst.svg",
      strategist: "/images/icons/strategist.svg",
      points: [
        "Interviews with Client about the idea, vision and market",
        "Questionnaires",
        "User stories",
        "Market analysis",
        "Self documentation",
        "Traceability Matrix",
        "User experience observations",
        "Proposed solutions and suggestions",
      ],
    },
    {
      title: "Define and Refine",
      image: "/images/define-refine.jpg",
      alternate: "Define and Refine",
      analyst: "/images/icons/analyst.svg",
      strategist: "/images/icons/strategist.svg",
      points: [
        "Brainstorming, organizing and linking key information",
        "Visualize Information Architecture",
        "Better review of Project Scope",
        "Identify content and information gaps",
        "Complete product review all-at-once",
        "Identify key modules",
        "Prioritize features",
      ],
    },
    {
      title: "Lean UX Process",
      image: "/images/ux-process.jpg",
      alternate: "Lean UX Process",
      analyst: "/images/icons/analyst.svg",
      strategist: "/images/icons/strategist.svg",
      points: [
        "Visual understanding of a page",
        "Illustrate key features of the solution",
        "Bringing Usability to the forefront",
        "Validate hypothesis about content and interaction strategy",
        "Reduced risks in actual Design Process",
      ],
    },
    {
      title: "UI/UX Design",
      image: "/images/define-refine.jpg",
      alternate: "UI/UX Design",
      analyst: "/images/icons/analyst.svg",
      strategist: "/images/icons/strategist.svg",
      points: [
        "Modern UI patterns",
        "Flat + Minimal + Material Approach",
        "Keeps Information at the Center (Minimum interference between User and Design)",
        "Engage the User Quickly",
        "Natural interaction methods",
        "MoSCoW Principal – prioritizing (Must have, Should have, Could have, Would have)",
        "Micro interactions",
      ],
    },
  ],
};
